"""empty message

Revision ID: 2caf7ebab15f
Revises: 62353aa37807
Create Date: 2020-06-29 14:37:47.556650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2caf7ebab15f'
down_revision = '62353aa37807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('imgurl', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'imgurl')
    # ### end Alembic commands ###
